import type { ActivistArtEvent } from "@/lib/events-types";

/**
 * AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
 * Generated by scripts/fetch-events.js
 * Source: Indy Arts Council (indyarts.org)
 * Last updated: 2025-12-11T01:32:17.247Z
 */
export const eventsData: ActivistArtEvent[] = [
  {
    "id": "20f78720-d755-4de7-92e5-e41af487e4db",
    "title": "Epicurean Holiday Night Market",
    "startDate": "2025-12-19",
    "city": "1060 N Capitol Ave",
    "state": "IN",
    "venue": "1060 N Capitol Ave, Indianapolis, IN 46204",
    "eventType": "community",
    "description": "<p>Come enjoy cozy vibes, food, hot chocolate, a photobooth, art, and light music and good vibes as always!</p>...",
    "causeTags": [
      "Community"
    ],
    "url": "https://indyarts.org/events"
  },
  {
    "id": "20f78720-d755-4de7-92e5-e41af487e4db",
    "title": "First Friday Gallery Opening: January 2026",
    "startDate": "2026-01-02",
    "city": "1505 North Delaware Street<br/>Indianapolis",
    "state": "IN",
    "venue": "1505 North Delaware Street<br/>Indianapolis, IN 46202",
    "eventType": "community",
    "description": "<p>On January 2nd, from 6-9pm, join us for First Friday! Enjoy these openings:</p>...",
    "causeTags": [
      "Community"
    ],
    "url": "https://indyarts.org/events"
  },
  {
    "id": "20f78720-d755-4de7-92e5-e41af487e4db",
    "title": "Holiday Bazaar",
    "startDate": "2025-12-13",
    "city": "1505 North Delaware Street<br/>Indianapolis",
    "state": "IN",
    "venue": "1505 North Delaware Street<br/>Indianapolis, IN 46202",
    "eventType": "community",
    "description": "<p>Shop unique gifts and treasures from around the world and experience the magic of the season through cultures from around the globe! Join us for an...",
    "causeTags": [
      "Community"
    ],
    "url": "https://indyarts.org/events"
  },
  {
    "id": "20f78720-d755-4de7-92e5-e41af487e4db",
    "title": "re•creation Family Game Night",
    "startDate": "2025-12-17",
    "city": "3328 East 10th St Suite C<br/>Indianapolis",
    "state": "IN",
    "venue": "3328 East 10th St Suite C<br/>Indianapolis, IN 46201",
    "eventType": "community",
    "description": "<p>Bring the whole family out for Family Game Night inside the re•creation exhibition! Explore interactive art, play together, and rediscover joy thro...",
    "causeTags": [
      "Community"
    ],
    "url": "https://indyarts.org/events"
  },
  {
    "id": "20f78720-d755-4de7-92e5-e41af487e4db",
    "title": "York Automotive Concert Series: Jim Messina",
    "startDate": "2026-03-21",
    "city": "3328 East 10th St Suite C<br/>Indianapolis",
    "state": "IN",
    "venue": "3328 East 10th St Suite C<br/>Indianapolis, IN 46201",
    "eventType": "community",
    "description": "<p>Delivering a delightful set of music, an evening full of wonderful memories, and fabulous insights into his celebrated career!</p>...",
    "causeTags": [
      "Community"
    ],
    "url": "https://indyarts.org/events"
  },
  {
    "id": "20f78720-d755-4de7-92e5-e41af487e4db",
    "title": "Central Indiana Dance Ensemble’s 26th Annual The Nutcracker",
    "startDate": "2025-12-12",
    "city": "3328 East 10th St Suite C<br/>Indianapolis",
    "state": "IN",
    "venue": "3328 East 10th St Suite C<br/>Indianapolis, IN 46201",
    "eventType": "community",
    "description": "<p>Central Indiana Dance Ensemble, a pre-professional resident company of the Allied Solutions Center for Performing Arts, presents a beloved classic,...",
    "causeTags": [
      "Community"
    ],
    "url": "https://indyarts.org/events"
  },
  {
    "id": "20f78720-d755-4de7-92e5-e41af487e4db",
    "title": "Harp Twins Rockin’ Christmas Concert featuring the Volfgang Twins",
    "startDate": "2025-12-19",
    "city": "3328 East 10th St Suite C<br/>Indianapolis",
    "state": "IN",
    "venue": "3328 East 10th St Suite C<br/>Indianapolis, IN 46201",
    "eventType": "community",
    "description": "<p>Join the world-renowned Harp Twins for this family-friendly concert full of magical winter music, Christmas classics, comedy, stories, and a sprink...",
    "causeTags": [
      "Community"
    ],
    "url": "https://indyarts.org/events"
  },
  {
    "id": "20f78720-d755-4de7-92e5-e41af487e4db",
    "title": "Real Love Baby – Reception",
    "startDate": "2026-02-13",
    "city": "3328 East 10th St Suite C<br/>Indianapolis",
    "state": "IN",
    "venue": "3328 East 10th St Suite C<br/>Indianapolis, IN 46201",
    "eventType": "community",
    "description": "<p>Opening reception for Real Love Baby, a love show at the Garfield Park Art Center, curated by Lexi Musselman</p>...",
    "causeTags": [
      "Community"
    ],
    "url": "https://indyarts.org/events"
  }
];
