/**
 * Fetch real Indiana art events from Indy Arts Council.
 * 
 * SOURCE: https://indyarts.org/feed/calendar/
 * FORMAT: ICS / iCal
 */

const https = require('https');
const fs = require('fs');
const path = require('path');

const TARGET_FILE = path.join(__dirname, '../src/lib/events-data.ts');
const FEED_URL = 'https://indyarts.org/feed/calendar/';

function fetch(url) {
    return new Promise((resolve, reject) => {
        https.get(url, (res) => {
            if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
                return fetch(res.headers.location).then(resolve).catch(reject);
            }
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => resolve(data));
            res.on('error', reject);
        });
    });
}

function parseICSDate(icsDate) {
    if (!icsDate) return '';
    // Format: 20251219T000000 or 20251219
    const match = icsDate.match(/^(\d{4})(\d{2})(\d{2})/);
    if (match) {
        return `${match[1]}-${match[2]}-${match[3]}`;
    }
    return icsDate;
}

function unescapeICS(str) {
    if (!str) return '';
    return str.replace(/\\,/g, ',').replace(/\\;/g, ';').replace(/\\n/g, '\n').replace(/\\\\/g, '\\');
}

async function main() {
    console.log(`Fetching events from ${FEED_URL}...`);
    try {
        const icsData = await fetch(FEED_URL);

        // Split by VEVENT
        const eventsRaw = icsData.split('BEGIN:VEVENT').slice(1);

        const events = eventsRaw.map((block, i) => {
            // Extract fields
            const summaryMatch = block.match(/SUMMARY:(.*?)(\r\n|\n)/);
            const descMatch = block.match(/DESCRIPTION:(.*?)(\r\n|\n)/); // Simple one-line match, strictly might be multi-line
            const startMatch = block.match(/DTSTART(?:;[^:]*)?:(\d+T?\d*)/);
            const locationMatch = block.match(/LOCATION:(.*?)(\r\n|\n)/);
            const urlMatch = block.match(/URL:(.*?)(\r\n|\n)/);
            const uidMatch = block.match(/UID:(.*?)(\r\n|\n)/);

            const title = summaryMatch ? unescapeICS(summaryMatch[1]) : 'Untitled Event';
            const startDate = startMatch ? parseICSDate(startMatch[1]) : '';
            const location = locationMatch ? unescapeICS(locationMatch[1]) : 'Indianapolis, IN';

            // Rough heuristic for city
            let city = 'Indianapolis';
            if (location.includes(',')) {
                city = location.split(',')[0].trim();
            }

            return {
                id: uidMatch ? uidMatch[1].trim() : `evt-indy-${i}`,
                title: title,
                startDate: startDate,
                city: city,
                state: "IN",
                venue: location,
                eventType: "community", // Default
                description: descMatch ? unescapeICS(descMatch[1]).slice(0, 150) + '...' : undefined,
                causeTags: ["Community"], // Placeholder
                url: urlMatch ? urlMatch[1].trim() : "https://indyarts.org/events"
            };
        }).filter(e => e.startDate.startsWith('20')); // Basic filter for valid dates

        console.log(`Found ${events.length} events.`);

        const fileContent = `import type { ActivistArtEvent } from "@/lib/events-types";

/**
 * AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
 * Generated by scripts/fetch-events.js
 * Source: Indy Arts Council (indyarts.org)
 * Last updated: ${new Date().toISOString()}
 */
export const eventsData: ActivistArtEvent[] = ${JSON.stringify(events.slice(0, 20), null, 2)};
`;

        fs.writeFileSync(TARGET_FILE, fileContent, 'utf8');
        console.log(`Successfully wrote ${events.slice(0, 20).length} events to ${TARGET_FILE}`);

    } catch (err) {
        console.error('Error fetching events:', err);
        process.exit(1);
    }
}

main();
